---
- name: slurp module demo
  hosts: 54.87.163.254
  become: false
  vars: 
     remotefile: "/proc/cpuinfo"
  tasks:
    - name: slurp remote file
     ansible.builtin.slurp:
       src: "{{ remotefile }}"
     register: slurpfile
     
     - name: print remote file
       ansible.builtin.debug:
         msg: "{{ slurpfile['content'] | b64deode }}"
